config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :blogs
  root to: 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body
end

app/models/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user
  end

  def guest_user
    guest = GuestUser.new
    guest.name = "Guest User"
    guest.first_name = "Guest"
    guest.last_name = "User"
    guest.email = "guest.user@example.com"
    guest
  end
end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :first_name, :last_name, :email
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include CurrentUserConcern
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], user: {except: [:destroy, :new, :update, :edit]}, site_admin: :all

  layout 'blogs'
  # GET /blogs
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /blogs/1
  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern
  
  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper
    if current_user.is_a?(GuestUser)
      (link_to 'Register', new_user_registration_path, class: 'nav-link') +
      "<br>".html_safe +
      (link_to 'Login', new_user_session_path, class: 'nav-link')
    else
      link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link'
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog_footer.html.erb
<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/blogs/_blog_masthead.html.erb
<header>
  <div class="blog-masthead">
    <div class="container">
      <nav class="nav">
        <%= link_to 'Blog', root_path, class: 'nav-link active' %>
        <%= login_helper %>
        <%= link_to 'New Blog', new_blog_path, class: 'nav-link' if logged_in?(:site_admin) %>
      </nav>
    </div>
  </div>

  <div class="blog-header">
    <div class="container">
      <h1 class="blog-title">BlogApp</h1>
      <p class="lead blog-description"><%= current_user.first_name %>, welcome to my blogApp!</p>
      <p id="notice"><%= notice %></p>
      <p id="alert"><%= alert %></p>
    </div>
  </div>
</header>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="role="main" class="container"">
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4 blog-main">
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, id: :blog_title, class: 'form-control' %>
          <%= form.label :body %>
          <%= form.text_area :body, id: :blog_body, class: 'form-control' %>
          <%= form.submit "Submit", class: 'btn btn-outline-primary' %>
          <%= link_to 'Back', blogs_path, class: 'btn btn-outline-secondary' %>
        </div>
      </div>
      <div class="col-md-4">
      </div>
    </div>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<main role="main" class="container">
  <div class="row">
    <div class="col-sm-8 blog-main">
      <% @blogs.each do |blog| %>
        <div class="blog-post">
          <div class="">
            <%= link_to blog.title, blog, class: 'blog-post-title' %>
          </div>

          <div class="blog-padding">
            <%= image_tag blog.thumb_image %>
          </div>

          <div class="blog-padding">
            <%= blog.body %>
          </div>
        </div>

        <nav class="blog-pagination">
          <a class="btn btn-outline-primary" href="#">Older</a>
          <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
          <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-outline-primary' if logged_in?(:site_admin) %>
          <%= link_to 'Destroy', blog, class: 'btn btn-outline-primary', method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
        </nav>
      <% end %>
    </div>

    <aside class="col-sm-3 ml-sm-auto blog-sidebar">
      <div class="sidebar-module sidebar-module-inset">
        <h4>About this blog</h4>
        <p>These are a study of how rails works, nothing special here... YET!</p>
      </div>

      <div class="sidebar-module">
        <h4>Social-Links</h4>
        <ol class="list-unstyled social-links">
          <li><%= link_to fa_icon("github"), "https://github.com/flouu" %></li>
          <li><%= link_to fa_icon("facebook"), "https://facebook.com" %></li>
          <li><%= link_to fa_icon("twitter"), "https://twitter.com" %></li>
        </ol>
      </div>
    </aside>
  </div>
</main>

app/views/blogs/new.html.erb
<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>

  <%= @blog.title %>
</p>
<%= image_tag @blog.main_image %>
<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog)  if logged_in?(:site_admin) %> /
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/blogs.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppLayout</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Raleway|Roboto" rel="stylesheet">
  </head>

  <body>
    <%= render 'blog_masthead' %>

    <%= yield %>

    <%= render 'blog_footer' %>
  </body>
</html>